# Generated by Django 6.0.3 on 2026-04-20 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieteikumaTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statuss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pieteikums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=200)),
                ('apraksts', models.TextField(blank=True)),
                ('izveidots', models.DateTimeField(auto_now_add=True)),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tips', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pieteikumi.pieteikumatips')),
                ('statuss', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pieteikumi.statuss')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_statuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_end', to='pieteikumi.statuss')),
                ('pieteikuma_tips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pieteikumi.pieteikumatips')),
                ('start_statuss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_start', to='pieteikumi.statuss')),
            ],
        ),
    ]
